ALTER TABLE "api_keys" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "api_keys" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "billing_period_items" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "billing_period_items" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "billing_periods" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "billing_periods" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "billing_runs" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "billing_runs" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "catalogs" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "catalogs" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "checkout_sessions" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "checkout_sessions" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "countries" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "countries" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "discount_redemptions" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "discount_redemptions" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "discounts" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "discounts" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "fee_calculations" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "fee_calculations" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "files" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "files" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "invoice_line_items" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "invoice_line_items" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "links" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "links" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "memberships" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "memberships" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "payment_methods" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "payment_methods" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "prices" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "prices" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "proper_nouns" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "proper_nouns" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "purchase_access_sessions" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "purchase_access_sessions" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "purchases" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "purchases" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "subscription_items" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "subscription_items" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "usage_events" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "usage_events" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "usage_meters" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "usage_meters" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "updated_by_commit" text;