ALTER TABLE "api_keys" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "api_keys" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "billing_period_items" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "billing_period_items" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "billing_periods" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "billing_periods" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "billing_runs" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "billing_runs" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "catalogs" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "catalogs" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "checkout_sessions" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "checkout_sessions" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "countries" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "countries" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "discount_redemptions" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "discount_redemptions" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "discounts" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "discounts" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "fee_calculations" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "fee_calculations" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "files" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "files" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "invoice_line_items" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "invoice_line_items" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "invoices" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "invoices" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "links" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "links" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "memberships" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "memberships" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "payment_methods" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "payment_methods" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "prices" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "prices" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "proper_nouns" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "proper_nouns" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "purchase_access_sessions" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "purchase_access_sessions" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "purchases" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "purchases" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "subscription_items" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "subscription_items" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "usage_events" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "usage_events" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "usage_meters" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "usage_meters" ADD COLUMN "updated_by_commit" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "created_by_commit" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "updated_by_commit" text;