ALTER POLICY "Enable select for own organizations" ON "api_keys" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable insert for own organizations" ON "api_keys" TO merchant WITH CHECK ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable delete for own organizations" ON "api_keys" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (billing_period_items)" ON "billing_period_items" TO merchant USING ("billing_period_id" in (select "id" from "billing_periods" where "subscription_id" in (select "id" from "subscriptions" where "organization_id"=current_organization_id())));--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (billing_periods)" ON "billing_periods" TO merchant USING ("subscription_id" in (select "id" from "subscriptions" where "organization_id"=current_organization_id()));--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (billing_runs)" ON "billing_runs" TO merchant USING ("billing_period_id" in (select "id" from "billing_periods" where "subscription_id" in (select "id" from "subscriptions" where "organization_id"=current_organization_id())));--> statement-breakpoint
ALTER POLICY "Enable all actions for discounts in own organization" ON "checkout_sessions" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable all actions for own organizations" ON "customers" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (discount_redemptions)" ON "discount_redemptions" TO merchant USING ("discount_id" in (select "id" from "discounts" where "organization_id"=current_organization_id()));--> statement-breakpoint
ALTER POLICY "Enable all actions for discounts in own organization" ON "discounts" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable insert for own organizations" ON "events" TO merchant WITH CHECK ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable all actions for own organization" ON "events" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (features)" ON "features" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable select for own organization" ON "fee_calculations" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (invoices)" ON "invoices" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (ledger_accounts)" ON "ledger_accounts" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (ledger_entries)" ON "ledger_entries" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (ledger_transactions)" ON "ledger_transactions" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable select for own organization" ON "payments" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable update for own organization" ON "payments" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (pricing_models)" ON "pricing_models" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (product_features)" ON "product_features" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (products)" ON "products" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (purchases)" ON "purchases" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (refunds)" ON "refunds" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (subscription_meter_period_calculations)" ON "subscription_meter_period_calculations" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (usage_credit_applications)" ON "usage_credit_applications" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (usage_credit_balance_adjustments)" ON "usage_credit_balance_adjustments" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (usage_credits)" ON "usage_credits" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (usage_events)" ON "usage_events" TO merchant USING ("customer_id" in (select "id" from "customers" where "organization_id"=current_organization_id()));--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (usage_meters)" ON "usage_meters" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable read for own organizations (webhooks)" ON "webhooks" TO merchant USING ("organization_id" = current_organization_id());--> statement-breakpoint
ALTER POLICY "Enable all actions for discounts in own organization" ON "checkout_sessions" RENAME TO "Enable all actions for checkout_sessions in own organization";