'use client'

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { DetailLabel } from '@/components/DetailLabel'
import { trpc } from '@/app/_trpc/client'
import { useCopyTextHandler } from '@/app/hooks/useCopyTextHandler'

interface PricingModelIntegrationGuideModalProps {
  isOpen: boolean
  setIsOpen: (isOpen: boolean) => void
  pricingModelId: string
}

export function PricingModelIntegrationGuideModal({
  isOpen,
  setIsOpen,
  pricingModelId,
}: PricingModelIntegrationGuideModalProps) {
  const { data, isLoading } =
    trpc.pricingModels.getIntegrationGuide.useQuery(
      { id: pricingModelId },
      { enabled: isOpen }
    )

  const integrationGuide = data?.integrationGuide ?? ''
  const copyHandler = useCopyTextHandler({ text: integrationGuide })

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogContent className="flex max-h-[90vh] flex-col sm:max-w-5xl">
        <DialogHeader className="flex-shrink-0">
          <DialogTitle>Integration Guide</DialogTitle>
        </DialogHeader>
        <div
          className="flex-1 min-h-0 flex flex-col overflow-y-auto"
          style={{ padding: '4px' }}
        >
          <div
            style={{ margin: '-4px' }}
            className="flex-1 flex flex-col"
          >
            <div className="flex-1 flex flex-col gap-6">
              <div className="flex-1 flex flex-col gap-2 min-h-0">
                <div className="flex items-center justify-between flex-shrink-0">
                  <Label htmlFor="integration-guide">Markdown</Label>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={copyHandler}
                    disabled={isLoading || !integrationGuide}
                  >
                    Copy to Clipboard
                  </Button>
                </div>
                <div className="flex-1 min-h-[400px] flex flex-col relative">
                  <Textarea
                    id="integration-guide"
                    readOnly
                    value={
                      isLoading ? 'Loading...' : integrationGuide
                    }
                    placeholder="No integration guide available"
                    className="absolute inset-0 font-mono text-sm"
                    textareaClassName="h-full w-full resize-none min-h-0"
                  />
                </div>
              </div>
              <div className="flex-shrink-0">
                <DetailLabel
                  label="Note"
                  value="Generated by AI, verify integration works as intended before you go live"
                />
              </div>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
