name: Build and deploy Flowglad Next Staging

on:
  push:
    branches: [main]  # Adjust this to match your primary branch

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  NEXT_PUBLIC_CDN_URL: ${{ secrets.NEXT_PUBLIC_CDN_URL }}
  TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
  FLOWGLAD_NEXT_VERCEL_PROJECT_NAME: ${{ secrets.FLOWGLAD_NEXT_VERCEL_PROJECT_NAME }}

jobs:
  deploy-staging:
    uses: ./.github/workflows/build-and-deploy-flowglad-next.yml
    with:
      environment: preview
    secrets: inherit
