name: Build and deploy Hosted Billing Staging

on:
  push:
    branches: [main]  # Adjust this to match your primary branch

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  HOSTED_BILLING_VERCEL_PROJECT_ID: ${{ secrets.HOSTED_BILLING_VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  NEXT_PUBLIC_CDN_URL: ${{ secrets.NEXT_PUBLIC_CDN_URL }}
  HOSTED_BILLING_VERCEL_PROJECT_NAME: ${{ secrets.HOSTED_BILLING_VERCEL_PROJECT_NAME }}

jobs:
  deploy-staging:
    uses: ./.github/workflows/build-and-deploy-hosted-billing.yml
    with:
      environment: preview
    secrets: inherit

  merge-main-to-stable:
    needs: deploy-staging  # This will only run after deploy-staging succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Need full history for merging
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Rebase stable onto main
        run: |
          git fetch origin stable
          git checkout stable
          git pull origin stable
          git rebase origin/main
          git push --force-with-lease origin stable 