name: Build and Deploy Production

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - preview
          - production

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  NEXT_PUBLIC_CDN_URL: ${{ secrets.NEXT_PUBLIC_CDN_URL }}
  HOSTED_BILLING_SENTRY_AUTH_TOKEN: ${{ secrets.HOSTED_BILLING_SENTRY_AUTH_TOKEN }}

jobs:
  deploy-flowglad-next-prod:
    uses: ./.github/workflows/build-and-deploy-flowglad-next.yml
    with:
      environment: production
    secrets: inherit
