name: Merge main to staging

# This workflow is triggered by a push to the main branch with changes to the platform/flowglad-next directory
# and merges main into staging
permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'platform/flowglad-next/**'

jobs:
  merge-main-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.AGREE_PERSONAL_ACCESS_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email agree.ahmed@gmail.com

      - name: Merge main to staging
        run: |
          git checkout staging
          git merge --no-ff main -m "Merge main into staging"
          git push "https://${{ secrets.AGREE_PERSONAL_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" staging
